---
# tasks file for lighthouse
- name: Install utils
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - nginx
- name: Apply nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
- name: Clone lighthouse repository
  git:
    repo: "{{ lighthouse_url }}"
    dest: "{{ lighthouse_dir }}"
    version: master
- name: Apply config
  template:
    src: lighthouse_nginx.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: 0644
  notify: Nginx reload